"""add_profile_fields_to_users

Revision ID: 15c9773f0bf9
Revises: f746db8ef4df
Create Date: 2026-02-26 16:37:01.861335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15c9773f0bf9'
down_revision: Union[str, Sequence[str], None] = 'f746db8ef4df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('title', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('company', sa.String(), nullable=True))
    op.add_column('users', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('users', sa.Column('team_size', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('pain_points', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('notif_product', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notif_community', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notif_feedback', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('group', sa.String(), nullable=True))
    op.add_column('users', sa.Column('access_tier', sa.String(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'access_tier')
    op.drop_column('users', 'group')
    op.drop_column('users', 'notif_feedback')
    op.drop_column('users', 'notif_community')
    op.drop_column('users', 'notif_product')
    op.drop_column('users', 'pain_points')
    op.drop_column('users', 'country')
    op.drop_column('users', 'team_size')
    op.drop_column('users', 'industry')
    op.drop_column('users', 'company')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'title')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
