"""create_community_debates_and_replies_tables

Revision ID: 8bea5301f316
Revises: e6f423b37193
Create Date: 2026-03-12 11:44:13.175676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bea5301f316'
down_revision: Union[str, Sequence[str], None] = 'e6f423b37193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_debates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_debates_category'), 'community_debates', ['category'], unique=False)
    op.create_index(op.f('ix_community_debates_created_at'), 'community_debates', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_debates_created_by_user_id'), 'community_debates', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_community_debates_last_activity_at'), 'community_debates', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_community_debates_slug'), 'community_debates', ['slug'], unique=True)
    op.create_table('community_debate_replies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('debate_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['debate_id'], ['community_debates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_debate_replies_created_at'), 'community_debate_replies', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_debate_replies_debate_id'), 'community_debate_replies', ['debate_id'], unique=False)
    op.create_index(op.f('ix_community_debate_replies_user_id'), 'community_debate_replies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_debate_replies_user_id'), table_name='community_debate_replies')
    op.drop_index(op.f('ix_community_debate_replies_debate_id'), table_name='community_debate_replies')
    op.drop_index(op.f('ix_community_debate_replies_created_at'), table_name='community_debate_replies')
    op.drop_table('community_debate_replies')
    op.drop_index(op.f('ix_community_debates_slug'), table_name='community_debates')
    op.drop_index(op.f('ix_community_debates_last_activity_at'), table_name='community_debates')
    op.drop_index(op.f('ix_community_debates_created_by_user_id'), table_name='community_debates')
    op.drop_index(op.f('ix_community_debates_created_at'), table_name='community_debates')
    op.drop_index(op.f('ix_community_debates_category'), table_name='community_debates')
    op.drop_table('community_debates')
    # ### end Alembic commands ###
